#!/bin/sh

. /lib/functions/network.sh                                      
                                                                
P_INTF=phantap

network_get_device P_BRIDGE $P_INTF                             
[ -z "$P_BRIDGE" ] && { echo "Bridge not ready"; exit; }        
P_BR_MAC=$(cat /sys/class/net/$P_BRIDGE/address)                
                                                                         
network_get_ipaddr P_BR_IP $P_INTF                              
[ -z "$P_BR_IP" ] && { echo "Bridge IP not assigned"; exit; }   

network_get_gateway P_GW_FAKEIP $P_INTF true                    
[ -z "$P_GW_FAKEIP" ] && { P_GW_FAKEIP="169.254.66.101"; }

NET="$1"
[ -z "$NET" ] && { echo "No argument given"; exit; }

/sbin/ip route add $NET via $P_GW_FAKEIP dev $P_BRIDGE
